/**
* simplemonitor API generated from simplemonitor.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* SimplemonitorJsonObject.h
*
*
*/

#pragma once


#include "JsonObjectBase.h"

#include "polycube/services/cube.h"

namespace polycube {
namespace service {
namespace model {

enum class SimplemonitorIngressActionEnum {
  DROP, PASS, SLOWPATH
};
enum class SimplemonitorEgressActionEnum {
  DROP, PASS, SLOWPATH
};

/// <summary>
///
/// </summary>
class  SimplemonitorJsonObject : public JsonObjectBase {
public:
  SimplemonitorJsonObject();
  SimplemonitorJsonObject(const nlohmann::json &json);
  ~SimplemonitorJsonObject() final = default;
  nlohmann::json toJson() const final;


  /// <summary>
  /// Name of the simplemonitor service
  /// </summary>
  std::string getName() const;
  void setName(std::string value);
  bool nameIsSet() const;

  /// <summary>
  /// Action performed on ingress packets
  /// </summary>
  SimplemonitorIngressActionEnum getIngressAction() const;
  void setIngressAction(SimplemonitorIngressActionEnum value);
  bool ingressActionIsSet() const;
  void unsetIngressAction();
  static std::string SimplemonitorIngressActionEnum_to_string(const SimplemonitorIngressActionEnum &value);
  static SimplemonitorIngressActionEnum string_to_SimplemonitorIngressActionEnum(const std::string &str);

  /// <summary>
  /// Action performed on egress packets
  /// </summary>
  SimplemonitorEgressActionEnum getEgressAction() const;
  void setEgressAction(SimplemonitorEgressActionEnum value);
  bool egressActionIsSet() const;
  void unsetEgressAction();
  static std::string SimplemonitorEgressActionEnum_to_string(const SimplemonitorEgressActionEnum &value);
  static SimplemonitorEgressActionEnum string_to_SimplemonitorEgressActionEnum(const std::string &str);

private:
  std::string m_name;
  bool m_nameIsSet;
  SimplemonitorIngressActionEnum m_ingressAction;
  bool m_ingressActionIsSet;
  SimplemonitorEgressActionEnum m_egressAction;
  bool m_egressActionIsSet;
};

}
}
}

