/**
* simplemonitor API generated from simplemonitor.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */


#include "SimplemonitorApiImpl.h"

namespace polycube {
namespace service {
namespace api {

using namespace polycube::service::model;

namespace SimplemonitorApiImpl {
namespace {
std::unordered_map<std::string, std::shared_ptr<Simplemonitor>> cubes;
std::mutex cubes_mutex;

std::shared_ptr<Simplemonitor> get_cube(const std::string &name) {
  std::lock_guard<std::mutex> guard(cubes_mutex);
  auto iter = cubes.find(name);
  if (iter == cubes.end()) {
    throw std::runtime_error("Cube " + name + " does not exist");
  }

  return iter->second;
}

}

void create_simplemonitor_by_id(const std::string &name, const SimplemonitorJsonObject &jsonObject) {
  {
    // check if name is valid before creating it
    std::lock_guard<std::mutex> guard(cubes_mutex);
    if (cubes.count(name) != 0) {
      throw std::runtime_error("There is already a cube with name " + name);
    }
  }
  auto ptr = std::make_shared<Simplemonitor>(name, jsonObject);
  std::unordered_map<std::string, std::shared_ptr<Simplemonitor>>::iterator iter;
  bool inserted;

  std::lock_guard<std::mutex> guard(cubes_mutex);
  std::tie(iter, inserted) = cubes.emplace(name, std::move(ptr));

  if (!inserted) {
    throw std::runtime_error("There is already a cube with name " + name);
  }
}

void replace_simplemonitor_by_id(const std::string &name, const SimplemonitorJsonObject &bridge){
  throw std::runtime_error("Method not supported!");
}

void delete_simplemonitor_by_id(const std::string &name) {
  std::lock_guard<std::mutex> guard(cubes_mutex);
  if (cubes.count(name) == 0) {
    throw std::runtime_error("Cube " + name + " does not exist");
  }
  cubes.erase(name);
}

std::vector<SimplemonitorJsonObject> read_simplemonitor_list_by_id() {
  std::vector<SimplemonitorJsonObject> jsonObject_vect;
  for(auto &i : cubes) {
    auto m = get_cube(i.first);
    jsonObject_vect.push_back(m->toJsonObject());
  }
  return jsonObject_vect;
}

std::vector<nlohmann::fifo_map<std::string, std::string>> read_simplemonitor_list_by_id_get_list() {
  std::vector<nlohmann::fifo_map<std::string, std::string>> r;
  for (auto &x : cubes) {
    nlohmann::fifo_map<std::string, std::string> m;
    m["name"] = x.first;
    r.push_back(std::move(m));
  }
  return r;
}

/**
* @brief   Read simplemonitor by ID
*
* Read operation of resource: simplemonitor*
*
* @param[in] name ID of name
*
* Responses:
* SimplemonitorJsonObject
*/
SimplemonitorJsonObject
read_simplemonitor_by_id(const std::string &name) {
  return get_cube(name)->toJsonObject();

}

/**
* @brief   Read egress-action by ID
*
* Read operation of resource: egress-action*
*
* @param[in] name ID of name
*
* Responses:
* SimplemonitorEgressActionEnum
*/
SimplemonitorEgressActionEnum
read_simplemonitor_egress_action_by_id(const std::string &name) {
  auto simplemonitor = get_cube(name);
  return simplemonitor->getEgressAction();

}

/**
* @brief   Read ingress-action by ID
*
* Read operation of resource: ingress-action*
*
* @param[in] name ID of name
*
* Responses:
* SimplemonitorIngressActionEnum
*/
SimplemonitorIngressActionEnum
read_simplemonitor_ingress_action_by_id(const std::string &name) {
  auto simplemonitor = get_cube(name);
  return simplemonitor->getIngressAction();

}

/**
* @brief   Update simplemonitor by ID
*
* Update operation of resource: simplemonitor*
*
* @param[in] name ID of name
* @param[in] value simplemonitorbody object
*
* Responses:
*
*/
void
update_simplemonitor_by_id(const std::string &name, const SimplemonitorJsonObject &value) {
  auto simplemonitor = get_cube(name);

  return simplemonitor->update(value);
}

/**
* @brief   Update egress-action by ID
*
* Update operation of resource: egress-action*
*
* @param[in] name ID of name
* @param[in] value Action performed on egress packets
*
* Responses:
*
*/
void
update_simplemonitor_egress_action_by_id(const std::string &name, const SimplemonitorEgressActionEnum &value) {
  auto simplemonitor = get_cube(name);

  return simplemonitor->setEgressAction(value);
}

/**
* @brief   Update ingress-action by ID
*
* Update operation of resource: ingress-action*
*
* @param[in] name ID of name
* @param[in] value Action performed on ingress packets
*
* Responses:
*
*/
void
update_simplemonitor_ingress_action_by_id(const std::string &name, const SimplemonitorIngressActionEnum &value) {
  auto simplemonitor = get_cube(name);

  return simplemonitor->setIngressAction(value);
}

/**
* @brief   Update simplemonitor by ID
*
* Update operation of resource: simplemonitor*
*
* @param[in] value simplemonitorbody object
*
* Responses:
*
*/
void
update_simplemonitor_list_by_id(const std::vector<SimplemonitorJsonObject> &value) {
  throw std::runtime_error("Method not supported");
}



/*
 * help related
 */


}

}
}
}

