/**
* simplemonitor API generated from simplemonitor.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* SimplemonitorApi.h
*
*/

#pragma once

#define POLYCUBE_SERVICE_NAME "simplemonitor"


#include "polycube/services/response.h"
#include "polycube/services/shared_lib_elements.h"

#include "SimplemonitorJsonObject.h"
#include <vector>


#ifdef __cplusplus
extern "C" {
#endif

Response create_simplemonitor_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response delete_simplemonitor_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_simplemonitor_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_simplemonitor_egress_action_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_simplemonitor_ingress_action_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response read_simplemonitor_list_by_id_handler(const char *name, const Key *keys, size_t num_keys);
Response replace_simplemonitor_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_simplemonitor_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_simplemonitor_egress_action_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_simplemonitor_ingress_action_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);
Response update_simplemonitor_list_by_id_handler(const char *name, const Key *keys, size_t num_keys, const char *value);

Response simplemonitor_list_by_id_help(const char *name, const Key *keys, size_t num_keys);


#ifdef __cplusplus
}
#endif

