/**
* simplemonitor API generated from simplemonitor.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* SimplemonitorApiImpl.h
*
*
*/

#pragma once


#include <memory>
#include <map>
#include <mutex>
#include "../Simplemonitor.h"

#include "SimplemonitorJsonObject.h"
#include <vector>

namespace polycube {
namespace service {
namespace api {

using namespace polycube::service::model;

namespace SimplemonitorApiImpl {
  void create_simplemonitor_by_id(const std::string &name, const SimplemonitorJsonObject &value);
  void delete_simplemonitor_by_id(const std::string &name);
  SimplemonitorJsonObject read_simplemonitor_by_id(const std::string &name);
  SimplemonitorEgressActionEnum read_simplemonitor_egress_action_by_id(const std::string &name);
  SimplemonitorIngressActionEnum read_simplemonitor_ingress_action_by_id(const std::string &name);
  std::vector<SimplemonitorJsonObject> read_simplemonitor_list_by_id();
  void replace_simplemonitor_by_id(const std::string &name, const SimplemonitorJsonObject &value);
  void update_simplemonitor_by_id(const std::string &name, const SimplemonitorJsonObject &value);
  void update_simplemonitor_egress_action_by_id(const std::string &name, const SimplemonitorEgressActionEnum &value);
  void update_simplemonitor_ingress_action_by_id(const std::string &name, const SimplemonitorIngressActionEnum &value);
  void update_simplemonitor_list_by_id(const std::vector<SimplemonitorJsonObject> &value);

  /* help related */
  std::vector<nlohmann::fifo_map<std::string, std::string>> read_simplemonitor_list_by_id_get_list();

}
}
}
}

