/**
* simplemonitor API generated from simplemonitor.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


#pragma once


#include "../base/SimplemonitorBase.h"



using namespace polycube::service::model;

class Simplemonitor : public SimplemonitorBase {
 public:
  Simplemonitor(const std::string name, const SimplemonitorJsonObject &conf);
  virtual ~Simplemonitor();

  void packet_in(polycube::service::Sense sense,
                 polycube::service::PacketInMetadata &md,
                 const std::vector<uint8_t> &packet) override;

  /// <summary>
  /// Action performed on ingress packets
  /// </summary>
  SimplemonitorIngressActionEnum getIngressAction() override;
  void setIngressAction(const SimplemonitorIngressActionEnum &value) override;

  /// <summary>
  /// Action performed on egress packets
  /// </summary>
  SimplemonitorEgressActionEnum getEgressAction() override;
  void setEgressAction(const SimplemonitorEgressActionEnum &value) override;
};
